// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Visu

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Dimm
void ui_Dimm_screen_init(void);
lv_obj_t *ui_Dimm;
void ui_event_DimmValue( lv_event_t * e);
lv_obj_t *ui_DimmValue;
lv_obj_t *ui_LabelName;
lv_obj_t *ui_LabelValue;


// SCREEN: ui_Color
void ui_Color_screen_init(void);
lv_obj_t *ui_Color;
lv_obj_t *ui_ColorValue;
lv_obj_t *ui_Label2;


// SCREEN: ui_Switch
void ui_Switch_screen_init(void);
lv_obj_t *ui_Switch;
lv_obj_t *ui_Label1;
lv_obj_t *ui_SwitchValue;


// SCREEN: ui_Message
void ui_Message_screen_init(void);
lv_obj_t *ui_Message;
lv_obj_t *ui_Label3;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_DimmValue( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_LabelValue, target, "", "%");
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Dimm_screen_init();
ui_Color_screen_init();
ui_Switch_screen_init();
ui_Message_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Dimm);
}
